# Who / what is a Community Manager? {#who}

_“Suddenly, my passion for open and transparent communication in science became ‘in-reach,’ and I became a community manager. It was surprisingly empowering to finally have a tangible concept to assign to my new career path!”_ - Elisha Wood-Charlson

A community engagement professional or community manager is someone who facilitates the activities of a community or collaboration and the interactions between its members. These activities may or may not take place within a dedicated online network, but likely involve the use of online tools. Community management may be considered as “in-reach” rather than “outreach” or public engagement. Typically, the role of a scientific community engagement manager (often part of the job description of a Center Director or Assistant Project Director) is to ensure cohesion in their community, yet they may have no formal training in the skills required to strategically do this. In science, the term community manager is gaining some traction within associations and within “infrastructure” organizations that serve scientists through the provision of specific tools and trainings. However, in a research collaboration context the term is rarely used and instead may be found within research development, program management, and research director roles.

_“Can dedicated community management improve collaborative research? Help scientists make connections across disciplines and across institutions, regions, and nations? Spread expertise throughout associations and networks?”_ - Dan Richman

In Section \@ref(rationalCM), we share data from a survey that explored why some organizations don’t have community managers, examine the funding landscape for these roles, the educational backgrounds, and formal training that community managers have. We finish by introducing some of their top challenges and further training needs. In Section \@ref(quickstart) provides a series of pieces with tips and tricks for new community managers, or those who have suddenly found themselves in such a role. Former Community Engagement Fellows share advice from their own experiences on topics including time management, setting priorities, networking, and how to work with stress. 


## Rational for community managers {#rationalCM}


## Quick start {#quickstart}


